### ISSUE TITLE
util: FindCanonicalURL incorrect usage of transform.Chain

### ISSUE THREAD

**Issue by icholy** [xarantolus/spacex-hop-bot#2]
Chains are stateful and not thread safe. You should be creating a new one for each call to `FindCanonicalURL`:

https://github.com/xarantolus/spacex-hop-bot/blob/d054b12b34943b8a9b102bef95fb23cc945bfba1/util/article.go#L21

**Comment by xarantolus** [comment]
Should be fixed now :) Thank you
